### PR TITLE
Translations - Add french translation (WIP)

### PR DESCRIPTION
**Pull request by Elgin675**
### When merged this pull request will:
- Add French translation on `danger` module (WIP)
- Add French translation on `main` module (WIP)
- Add French translation on `wp` module (WIP)
- Add French translation on `eventhandlers` module (WIP)

### CODE REVIEW

**Comment by jokoho48** [comment]
it looks like you worked with UTF-8 BOM and saved as UTF-8 what broke the hole encoding. i fixed it for now please double check your tools the next time 👍

**Comment by Elgin675** [comment]
@jokoho48 Thank you !
But can you share a .editorconfig file please ? Because I didn't do anything special on my side for broke the encoding.

**Comment by jokoho48** [comment]
@Elgin675 status?

**Comment by Elgin675** [comment]
@jokoho48 Not finished yet, but I'm still working ;) !

**Comment by jokoho48** [comment]
@Elgin675 what is the current status?

**Comment by nk3nny** [comment]
Hi @Elgin675, 

Happy to have your work, but I'm wondering what the progress on this is.  We're approaching 2.5.0 and 2.5.1 releases. :) 

-k

**Comment by Elgin675** [comment]
Hi @nk3nny :) !

I was unavailable for several months, so I haven't really been able to progress since.

And as my graphic card is broken, it's getting complicated to launch Arma to work on it :D !

I'd like to finish, but clearly it's not for now :( !

**Comment by nk3nny** [comment]
That is understandable :) 

I'm going to close this pull request for now. But we know where it is, so if yourself or another wants to do French translations, we know where to point them. 

Ken

**Pull request closed without merging**
