### PR TITLE
Add Debug Renderer

### PR DESCRIPTION
**Pull request by jokoho48**
The version in the video still had some bugs, but they should be fixed now
Preview video: https://youtu.be/2U6fLC8NWxk

### CODE REVIEW

**Comment by nk3nny** [comment]
Cool interface.  It would be a very useful expansion to mark group leaders in some manner and perhaps have a way to display information stored in the dangerMode variable.  (DangerMode queue and timeouts mainly). Either through this interface, or a similar one.

**Comment by jokoho48** [comment]
yes will do that.

**Comment by jokoho48** [comment]
is the DangerMode Only Important for the Leader or does every AI needs that?

**Comment by jokoho48** [comment]
i now added the DangerMode Stuff to Only Squad Leaders

**Comment by jokoho48** [comment]
https://i.imgur.com/XTC5FKY.jpg

**Comment by nk3nny** [comment]
_DangerMode_ is relevant mostly for the leader.  First array contains information relating to what the Squad has assessed earlier. 

Fourth entry gives information when the DangerMode will time out. That is-- the group will respond to contact by 'reacting' again. 

Of these, the first one is the most relevant

**Comment by nk3nny** [comment]
First entry is an array which is filled with numbers.  There will only be one entry of each number. Order of priority is lower is better. 

1, "Contact"
2, "Hide from tank/air craft"
3, "Manoeuvre" 
5, "Check nearby buildings"
6, "Call artillery"

At the current time. The intention is to add to these to expand more customized behavior. Such as  'Black Hawk Down' esque  swarms.

**Comment by nk3nny** [comment]
Picture is perfect.  Though for the sake of clarity, may be better to mark the unit as **group leader** rather than **squad leader** (which carries different connotations in the context of Arma.

**Comment by nk3nny** [comment]
Will happily Merge once ready.

**Pull request merged**
