### PR TITLE
Adds better support for MLRS artillery

### PR DESCRIPTION
**Pull request by nk3nny**
**Improves Dynamic Artillery support for MLRS style launchers.** 
- MLRS launchers will now shoot their entire magazine. Launchers with large magazines will still clump their salvos in 2's or 4's to ensure good spread on target. 
- MLRS launchers will have no check rounds-- which make them quite dangerous in numbers.

### CODE REVIEW

**Comment by rautamiekka** [comment]
I suppose the idea is to make sure the dynamic target, and everything around it, is gonna die ?

Or is this a bug fix of sorts ?

**Comment by diwako** [comment]
> I suppose the idea is to make sure the dynamic target, and everything around it, is gonna die ?
> 
> Or is this a bug fix of sorts ?

It is a lowkey feature request from someone from our discord server. They are developing MRLS artillery vehicle assets and asked if it was intended for them to shoot only one rocket at a time.
The current code more or less only simulates tube based artillery and is tweaked for gameplay. With this you can mark an artillery as MRLS, so it behaves a bit different and actually uses the rocket/missile salvo as an MRLS would do. Pretty much obliterating a whole area as their original intend is.

**Comment by rautamiekka** [comment]
Interesting, why not.

**Comment by nk3nny** [comment]
Remember to add Zeus interaction

**Review by jokoho48 — CHANGES_REQUESTED** [review]
Zeus Modules and Editor Modules missing. also TaskArtillery has header not updated

**Pull request merged**
