### PR TITLE
Update for Polish translation (LAMBS 2.5.1 RC4)

### PR DESCRIPTION
**Pull request by MiszczuZPolski**
Add missing translations for LAMBS danger, wp and main

### CODE REVIEW

**Comment by SzwedzikPL** [comment]
I suggest changing `wsparcie` to `posiłki`, `wsparcie` is to generic in my opinion. In vanilla, `Reinforcements` is also translated as `Posiłki`.

**Comment by MiszczuZPolski** [comment]
Ok, i will change it later.

**Comment by nk3nny** [comment]
<3 Thanks guys. This is great stuff.

**Review by veteran29 — APPROVED** [review]
LGTM

**Pull request merged**
