### PR TITLE
Optimize fnc_findClosedTarget

### PR DESCRIPTION
**Pull request by dedmen**
### When merged this pull request will:

1. Make fnc_findClosedTarget faster

### CODE REVIEW

**Comment by dedmen** [comment]
Also isn't the function name wrong?? A "Closed" target? That's not what this function does, the description is also wrong.

**Comment by jokoho48** [comment]
good catch @dedmen ... that goes properly on my head. feel free to fix the naming and header.

**Comment by dedmen** [comment]
its a public function though, so renaming might cause issues?

**Comment by jokoho48** [comment]
I think that was wrongly marked as public. we can just mark as private and change the name :P

**Comment by nk3nny** [comment]
Most of the functions in the danger_wp pbo are due a rewrite and rethink to match end user expectations. Wrongly marked public indeed. 

I will hold off merging until we've had a meeting in regards to direction and overall structure. Changes look good however.

**Comment by jokoho48** [comment]
@nk3nny I still think we should merge it because this will be a function that does not really will change. it is a simple getter/find function

**Comment by nk3nny** [comment]
You are absolutely right, @jokoho48. 

-k

**Pull request merged**
